import ServiceCard from "./ServiceCard";
import img1 from "../assets/code-monks1.png";
import img2 from "../assets/code-monks2.png";
import img3 from "../assets/codemonks3.jpg"; 
import img4 from "../assets/codemonks4.avif";
import img5 from "../assets/codemonks5.avif";
import "../Css/ServiceCard.css";

export default function ServiceCardTab(){
    return(
<div className="card1">
    <ServiceCard img ={img1} heading1 ="Mobile App Development" paragraph1="Scalable mobile apps for iOS & Android platforms."heading2="Mobile App Development" p1="At Code Monks, we help businesses redefine the way they connect with their customers through intelligent, fully customized Customer Relationship Management (CRM) solutions. In today’s competitive market, customer relationships are your biggest asset — and our CRM systems are built to strengthen, streamline, and scale those relationships like never before." p2="We design, implement, and optimize CRMs that do more than just store information. Our solutions automate repetitive tasks, centralize customer data, track every interaction, and deliver real-time insights to empower smarter business decisions. Whether it’s sales tracking, marketing automation, lead nurturing, customer service optimization, or advanced analytics, we ensure your CRM becomes the central hub of your customer operations."p3="From integrating your CRM with existing tools to creating custom workflows that match your business model, we tailor every solution for efficiency, usability, and growth."/>

    <ServiceCard className="card1"  img ={img2} heading1="Websites & Web Applications" paragraph1="Modern and scalable websites built with clean code." heading2="Websites & Web Applications" p1="At Code Monks, we help businesses embrace the power of the cloud to achieve greater agility, scalability, and cost efficiency. In today’s fast-paced digital landscape, traditional infrastructure can’t keep up with the demands of growth — which is why our cloud solutions are designed to give you the flexibility to adapt, innovate, and scale without limits." p2="Our services cover cloud migration, architecture design, deployment, integration, performance optimization, and ongoing management. Whether you choose public, private, or hybrid cloud infrastructure, we ensure your systems are secure, reliable, and tailored to your unique business needs."p3="We work with leading platforms such as AWS, Microsoft Azure, and Google Cloud to deliver robust solutions that enable real-time collaboration, seamless data accessibility, and advanced disaster recovery." />

    <ServiceCard className="card1" img ={img3}  heading1="CRM Solutions" paragraph1="Smarter sales, stronger relationships."heading2="CRM Solutions"p1="At Code Monks, we help businesses unlock the full potential of their data through advanced Artificial Intelligence (AI), Machine Learning (ML), and Data Science solutions. From predictive analytics and intelligent automation to personalized recommendations and pattern recognition, we create data-driven systems that deliver real business value." p2="Our expertise includes natural language processing, computer vision, predictive modeling, and big data analytics — enabling us to build solutions that not only process information but also learn, adapt, and improve over time."p3="Whether you need to optimize operations, enhance decision-making, or gain deeper customer insights, our AI and ML solutions are customized, scalable, and secure. With Code Monks, your data becomes more than just numbers — it becomes a strategic asset for innovation and growth."/>

    <ServiceCard className="card1" img ={img4}  heading1="Cloud Solutions" paragraph1="Scalable, secure, and ready for the future."heading2="Cloud Solutions"p1="At Code Monks, we help businesses embrace the power of the cloud to achieve greater agility, scalability, and cost efficiency. In today’s fast-paced digital landscape, traditional infrastructure can’t keep up with the demands of growth — which is why our cloud solutions are designed to give you the flexibility to adapt, innovate, and scale without limits." p2="Our services cover cloud migration, architecture design, deployment, integration, performance optimization, and ongoing management. Whether you choose public, private, or hybrid cloud infrastructure, we ensure your systems are secure, reliable, and tailored to your unique business needs."p3="We work with leading platforms such as AWS, Microsoft Azure, and Google Cloud to deliver robust solutions that enable real-time collaboration, seamless data accessibility, and advanced disaster recovery."/>

    <ServiceCard className="card1" img ={img5}  heading1="AI, ML & Data Science"paragraph1="Intelligent solutions that turn data into insights."heading2="AI, ML & Data Science"p1="At Code Monks, we help businesses unlock the full potential of their data through advanced Artificial Intelligence (AI), Machine Learning (ML), and Data Science solutions. From predictive analytics and intelligent automation to personalized recommendations and pattern recognition, we create data-driven systems that deliver real business value." p2="our expertise includes natural language processing, computer vision, predictive modeling, and big data analytics — enabling us to build solutions that not only process information but also learn, adapt, and improve over time."p3="Whether you need to optimize operations, enhance decision-making, or gain deeper customer insights, our AI and ML solutions are customized, scalable, and secure. With Code Monks, your data becomes more than just numbers — it becomes a strategic asset for innovation and growth."/>
</div>
    );
};